#!/bin/bash
# ===============================================
# Author: aliazhar < aliazhar0555@gmail.com >
# Contributor: -
# License: GNU General Public License v2.0
# ===============================================


# {[IMPORTANT]} Where PKGBUILD and clones will be stored; cDir which means 'cache directory'.
cDir=~/Packages
 
# Check if argument/package name is specified or not.
[ $# -eq 0 ] && echo "No packages specified" && exit 1

# Check if cache directory exists or not
if ! [ -d $cDir ]
  then
    echo "Error: Cache directory not found"
    echo "run 'mkdir -p $cDir' to solve it"
    exit 1
fi

if [ "$*" == "-si $2" ]; then
  # Check if directory with package name exists or not
  ! [ -d $cDir/$2 ] && git -C $cDir clone https://aur.archlinux.org/$2

  cd $cDir/$2

    makepkg -si
  else
    # Check if directory with package name exists or not
    ! [ -d $cDir/$@ ] && git -C $cDir clone https://aur.archlinux.org/$@

    cd $cDir/$@

    makepkg -s
fi

echo "APD has successfully build packages"
