#!/bin/bash
# ===============================================
# Author: aliazhar < aliazhar0555@gmail.com >
# Contributor: -
# License: GNU General Public License v2.0
# ===============================================


# {[IMPORTANT]} Where PKGBUILD and clones will be stored; cDir which means 'cache directory'.
cDir=~/Packages
 
# Check if argument/package name is specified or not.
[ $# -eq 0 ] && printf "No packages specified" && exit 1

# Check if cache directory exists or not
if ! [ -d $cDir ]
  then
    printf "Error: Cache directory not found"
    printf "run 'mkdir -p $cDir' to solve it"
    exit 1
fi

if [ "$*" == "-i $2" ]; then
    packageName = $2
    apdParams = '-si'
  else
    packageName = $@
    apdParams = '-s'
fi

# Check if directory with package name exists or not
! [ -d $cDir/$packageName ] && git -C $cDir clone https://aur.archlinux.org/$packageName

cd $cDir/$packageName

makepkg $apdParams

printf "APD has successfully build packages"
